export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const CHECKOUT = 'CHECKOUT';
export const CLEAN_CART ='CLEAN_CART;'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'


export const FETCH_DATA_REQUEST ='FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS ='FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR ='FETCH_DATA_ERROR'





